networks:
  tagsoft_network:
    driver: bridge

services:
  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - "./src:/var/www"
      - "./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    networks:
      - tagsoft_network
    
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_docker
    image: php:8.2-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
      - "./environment/php/local.ini:/usr/local/etc/php/local.ini"
    networks:
      - tagsoft_network