services:
  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    volumes:
      - "./src:/var/www"
      - "./environment/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php
    networks:
      - tagsoft_network
    
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_docker
    image: php:8.2-fpm
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - "./src:/var/www"
      - "./environment/php/local.ini:/usr/local/etc/php/local.ini"
    networks:
      - tagsoft_network

  db:
    image: mysql:latest
    container_name: db_docker
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: db_docker
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - db:/var/lib/mysql
      - ./environment/mysql/my.conf:/etc/mysql/my.conf
    networks:
      - tagsoft_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_docker
    restart: unless-stopped
    tty: true
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      #MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - tagsoft_network

networks:
  tagsoft_network:
    driver: bridge

volumes:
  db:
    driver: local